[package]
name = "will"
version = "0.1.0"
edition = "2021"

[package.metadata.artificial-will]
dist-group = "core"

[lib]
crate-type = ["cdylib"]

[dependencies]
bones-messages = { path = "../../vendor/bones/shared/bones-messages" }
game-messages = { path = "../game-messages" }
game-ui = { path = "../../vendor/bones/shared/game-ui" }
wit-bindgen = "0.59.0"
